/* Generated by powerful Codeforces Tool
 * Author: calabash_boy_love_15 
 * Time: 2019-05-15 11:00:02
 * Personal Code Template: https://github.com/4thcalabash/ACM-Code-Library
**/
#include <bits/stdc++.h>
using namespace std;
int s[maxn];
int n;
struct Linear_Basis{
    //basis vector
    int basis[22];
    //basis vector in origin data
    int num[22];
    void clear(){
        memset(basis,0,sizeof basis);
        memset(num,0,sizeof num);
    }
    void ins(int x){
        int bk = x;
        for (int i=20;i>=0;i--){
            if (x & (1<< i)){
                if (!basis[i]){basis[i] = x;num[i] = bk;break;}
                x ^= basis[i];
            }
        }
    }
    int count(){
        int cnt = 0;
        for (int i=0;i<=20;i++){
            cnt += (basis[i] != 0);
        }
        return cnt;
    }
    void debug(){
        _debug("basis : ");
        for (int i=0;i<=20;i++){
            if (basis[i])_debug("%d : %d",i,basis[i]);
        }
    }
}basis;
int main(){
    cin>>n;
    for (int i=1;i<=n;i++){
        cin>>s[i];
        basis.ins(s[i]);
    }
    return 0;
}
